"""added icon to categories migration

Revision ID: 21cd9df42606
Revises: 78b47f27bb02
Create Date: 2024-10-17 11:34:55.739594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21cd9df42606'
down_revision: Union[str, None] = '78b47f27bb02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('icon', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'icon')
    # ### end Alembic commands ###
