"""update budgets model migrations and relationships to include title

Revision ID: 3acb4ca8f29c
Revises: 6faf79524c1b
Create Date: 2024-10-20 18:35:58.971973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3acb4ca8f29c'
down_revision: Union[str, None] = '6faf79524c1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('title', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'title')
    # ### end Alembic commands ###
