"""add budgets model migrations and relationships

Revision ID: 6faf79524c1b
Revises: 35b1c765c5bb
Create Date: 2024-10-18 22:12:07.692149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6faf79524c1b'
down_revision: Union[str, None] = '35b1c765c5bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('icon', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'icon')
    # ### end Alembic commands ###
