"""added predefined_categories migration

Revision ID: b39c85b7efc7
Revises: fe44d0e2ee23
Create Date: 2024-10-04 16:28:44.390606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b39c85b7efc7'
down_revision: Union[str, None] = 'fe44d0e2ee23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
